Login: Anmelden
Logout: Abmelden
LoggedInAs name: Angemeldet als „#{name}“
SetPassword: Passwort ändern
Register: Registrieren

NavSubscriptions: Listenabonnements
NavLists: Listen verwalten
NavUsers: Benutzer verwalten
NavCategories: Kategorien verwalten
NavEvents: Termine

RoleNothing: (keine)
RoleConsumer: Benutzer
RoleInnerCircle: Mitglied im Inneren Zirkel™
RoleAdmin: Administrator

Verified: verifiziert
Unverified: unverifiziert

ListRoleNothing: nicht abonniert
ListRoleReceiver: Abonnent
ListRoleSender: Autor

List name@Text: Mailingliste „#{name}“
Lists: Mailinglisten
ListSubscribers: Listenabonnenten
AvailableLists: Verfügbare Mailinglisten
NewList: Mailingliste hinzufügen
EditList: Mailingliste bearbeiten
EditListFail: Die Mailingliste konnte nicht aktualisiert werden.
EditListSuccess name: Die Mailingliste „#{name}“ wurde aktualisiert.
CreateListFail: Die Mailingliste konnte nicht hinzugefügt werden.
CreateListSuccess name: Die Mailingliste „#{name}“ wurde hinzugefügt.
DeleteListFail: Die Mailingliste konnte nicht gelöscht werden.
DeleteListSuccess name: Die Mailingliste „#{name}“ wurde gelöscht.
DeleteListConfirm name: Möchten Sie die Mailingliste „#{name}“ wirklich löschen?
DeleteUserFail: Der Benutzer konnte nicht gelöscht werden.
DeleteUserSuccess name: Der Benutzer „#{name}“ wurde gelöscht.
DeleteUserConfirm name: Möchten Sie den Benutzer „#{name}“ wirklich löschen?
SendMessage: Nachricht versenden
SendMessageFail: Die Nachricht konnte nicht versendet werden.
SendMessageSuccess subject name: Die Nachricht „#{subject}“ wurde an die Liste „#{name}“ versendet.
Message: Nachricht
MessageEvents: Die folgenden Termine werden automatisch an ihre Nachricht angehängt:

NameField: Name
DescField: Beschreibung
HeadField: Kopfzeilen
FootField: Fußzeilen
LangField: Sprache
BodyField: Inhalt
SubjectField: Betreffzeile

SubscriptionStatus: Status
ListActions: Aktionen
SubscriberActions: Aktionen
UserActions: Aktionen
SubscriberCount: Abonnenten
SenderCount: Autoren
Subscriptions: Abonnements

Users: Benutzer
EmailAddress: Mailadresse
Role: Rolle
UserRole: Rolle
ChangeUserRole: Rolle ändern
VerifiedStatus: Verifikationsstatus
PromoteSubscriber: Zum Autor befördern
DemoteSubscriber: Zum Abonennten degradieren
ConfirmChangeRole name oldRole role: Möchten sie die Rolle des Benutzers „#{name}“ wirklich von „#{oldRole}“ zu „#{role}“ ändern?
ChangeRoleSuccess name role: Die Rolle des Benutzers „#{name}“ wurde zu „#{role}“ geändert.
ChangeRoleFail name: Die Rolle von „#{name}“ konnte nicht geändert werden.
ConfirmLogout: Möchten Sie sich wirklich abmelden?

ActionSubscribe: Abonnieren
ActionUnsubscribe: Abbestellen
ActionSendMessage: Nachricht verfassen
ActionEditList: Mailingliste bearbeiten
ActionDeleteList: Mailingliste löschen
ActionDeleteUser: Benutzer löschen
ActionEditCategory: Kategorie bearbeiten
ActionDeleteCategory: Kategorie löschen
ActionEditEvent: Termin bearbeiten
ActionDeleteEvent: Termin löschen
ActionListEvents: Listentermine

ChangeRoleButton: Rolle ändern
CancelButton: Abbrechen
ResetButton: Zurücksetzen
SubmitButton: Absenden
DeleteButton: Löschen
LogoutButton: Abmelden
SendMessageButton: Absenden
NewListButton: Hinzufügen
EditListButton: Aktualisieren
UnsubscribeButton: Austragen
AddEventButton: Hinzufügen

UnsubscribeFail name: Ungültiger Schlüssel — Sie konnten nicht aus der Mailingliste „#{name}“ ausgetragen werden.
UnsubscribeSuccess name: Sie wurden aus der Mailingliste „#{name}“ ausgetragen.
SubscribeSuccess name: Sie haben die Liste „#{name}“ abboniert.
Unsubscribe: Mailingliste abbestellen
UnsubscribeConfirm name: Wollen Sie sich wirklich aus der Mailingliste „#{name}“ austragen?

VerifyEmailSubject: minitrue: Verifizieren Sie ihre Mailadresse
VerifyEmailBody key url: Um ihre Mailadresse zu verifizieren, besuchen Sie #{url}.

LangEnglish: Englisch
LangGerman: Deutsch

Events: Veranstaltungen
EventName: Name
EventLocation: Veranstaltungsort
EventDescription: Beschreibung
EventDate: Datum
EventCategory: Kategorie
EventTime: Veranstaltungsbeginn
EventDateTime: Veranstaltungsbeginn
EventActions: Aktionen

Category name: Kategorie „#{name}“
Categories: Kategorien
CategoryName: Name
CategoryDescription: Beschreibung
CategoryActions: Aktionen
CategoryEvents name: Termine in der Kategorie „#{name}“
NewCategory: Kategorie hinzufügen
NewCategoryButton: Hinzufügen
EditCategoryButton: Aktualisieren
CreateCategoryFail: Die Kategorie konnte nicht erstellt werden.
CreateCategorySuccess name: Kategorie „#{name}“ erstellt.
EditCategoryFail: Die Kategorie konnte nicht aktualisiert werden.
EditCategorySuccess name: Kategorie „#{name}“ aktualisiert.
DeleteCategoryFail: Die Kategorie konnte nicht gelöscht werden.
DeleteCategorySuccess name: Kategorie „#{name}“ gelöscht.
DeleteCategoryConfirm name: Möchten Sie die Kategorie „#{name}“ wirklich löschen?

Event name: Termin „#{name}“
ListEvents name: Termine für Liste „#{name}“
NewEvent: Termin hinzufügen
NewEventButton: Hinzufügen
EditEvent: Termin bearbeiten
EditEventButton: Aktualisieren
CreateEventFail: Termin konnte nicht erstellt werden.
CreateEventSuccess name: Termin „#{name}“ erstellt.
EditEventFail: Termin konnte nicht aktualisiert werden.
EditEventSuccess name: Termin „#{name}“ aktualisiert.
DeleteEventFail: Termin konnte nicht gelöscht werden.
DeleteEventSuccess name: Termin „#{name}“ gelöscht.
DeleteEventConfirm name: Möchten Sie den Termin „#{name}“ wirklich löschen?