Login: Anmelden
Logout: Abmelden
LoggedInAs name: Angemeldet als „#{name}“
SetPassword: Passwort ändern
Register: Registrieren

NavSubscriptions: Listenabonnements
NavLists: Listen verwalten
NavUsers: Benutzer verwalten

RoleNothing: (keine)
RoleConsumer: Benutzer
RoleInnerCircle: Mitglied im Inneren Zirkel™
RoleAdmin: Administrator

Verified: verifiziert
Unverified: unverifiziert

ListRoleNothing: nicht abonniert
ListRoleReceiver: Abonnent
ListRoleSender: Autor

List name@Text: Mailingliste „#{name}“
Lists: Mailinglisten
ListSubscribers: Listenabonnenten
AvailableLists: Verfügbare Mailinglisten
NewList: Mailingliste hinzufügen
EditList: Mailingliste bearbeiten
EditListFail: Die Mailingliste konnte nicht aktualisiert werden.
EditListSuccess name: Die Mailingliste „#{name}“ wurde aktualisiert.
CreateListFail: Die Mailingliste konnte nicht hinzugefügt werden.
CreateListSuccess name: Die Mailingliste „#{name}“ wurde hinzugefügt.
DeleteListFail: Die Mailingliste konnte nicht gelöscht werden.
DeleteListSuccess name: Die Mailingliste „#{name}“ wurde gelöscht.
DeleteListConfirm name: Möchten Sie die Mailingliste „#{name}“ wirklich löschen?
DeleteUserFail: Der Benutzer konnte nicht gelöscht werden.
DeleteUserSuccess name: Der Benutzer „#{name}“ wurde gelöscht.
DeleteUserConfirm name: Möchten Sie den Benutzer „#{name}“ wirklich löschen?
SendMessage: Nachricht versenden
SendMessageFail: Die Nachricht konnte nicht versendet werden.
SendMessageSuccess subject name: Die Nachricht „#{subject}“ wurde an die Liste „#{name}“ versendet.

NameField: Name
DescField: Beschreibung
BodyField: Inhalt
SubjectField: Betreffzeile

SubscriptionStatus: Status
ListActions: Aktionen
SubscriberActions: Aktionen
UserActions: Aktionen
SubscriberCount: Abonnenten
SenderCount: Autoren
Subscriptions: Abonnements

Users: Benutzer
EmailAddress: Mailadresse
Role: Rolle
UserRole: Rolle
ChangeUserRole: Rolle ändern
VerifiedStatus: Verifikationsstatus
PromoteSubscriber: Zum Autor befördern
DemoteSubscriber: Zum Abonennten degradieren
ConfirmChangeRole name oldRole role: Möchten sie die Rolle des Benutzers „#{name}“ wirklich von „#{oldRole}“ zu „#{role}“ ändern?
ChangeRoleSuccess name role: Die Rolle des Benutzers „#{name}“ wurde zu „#{role}“ geändert.
ChangeRoleFail name: Die Rolle von „#{name}“ konnte nicht geändert werden.
ConfirmLogout: Möchten Sie sich wirklich abmelden?

ActionSubscribe: Abonnieren
ActionUnsubscribe: Abbestellen
ActionSendMessage: Nachricht verfassen
ActionEditList: Mailingliste bearbeiten
ActionDeleteList: Mailingliste löschen
ActionDeleteUser: Benutzer löschen

ChangeRoleButton: Rolle ändern
CancelButton: Abbrechen
ResetButton: Zurücksetzen
SubmitButton: Absenden
DeleteButton: Löschen
LogoutButton: Abmelden
SendMessageButton: Absenden
NewListButton: Hinzufügen
EditListButton: Aktualisieren
UnsubscribeButton: Austragen

UnsubscribeFail name: Ungültiger Schlüssel — Sie konnten nicht aus der Mailingliste „#{name}“ ausgetragen werden.
UnsubscribeSuccess name: Sie wurden aus der Mailingliste „#{name}“ ausgetragen.
Unsubscribe: Mailingliste abbestellen
UnsubscribeConfirm name: Wollen Sie sich wirklich aus der Mailingliste „#{name}“ austragen?

VerifyEmailSubject: minitrue: Verifizieren Sie ihre Mailadresse
VerifyEmailBody key url: Um ihre Mailadresse zu verifizieren, besuchen Sie #{url}.
