Login: Login
Logout: Logout
LoggedInAs name@Text: Logged in as “#{name}”
SetPassword: Change password
Register: Register

NavSubscriptions: List subscriptions
NavLists: Manage lists
NavUsers: Manage users

RoleNothing: (none)
RoleConsumer: User
RoleInnerCircle: Member of the Inner Circle™
RoleAdmin: Administrator

Verified: verified
Unverified: unverified

ListRoleNothing: not subscribed
ListRoleReceiver: Subscriber
ListRoleSender: Author

List name@Text: Mailing list “#{name}”
Lists: Mailing lists
ListSubscribers: List subscribers
AvailableLists: Available lists
NewList: New list
EditList: Edit list
EditListFail: Could not update list.
EditListSuccess name@Text: List “#{name}” updated.
CreateListFail: Could not create list.
CreateListSuccess name@Text: List “#{name}” created.
DeleteListFail: Could not delete list.
DeleteListSuccess name@Text: List “#{name}” deleted.
DeleteListConfirm name@Text: Really delete List “#{name}”?
DeleteUserFail: Could not delete user.
DeleteUserSuccess name@Text: User “#{name}” deleted.
DeleteUserConfirm name@Text: Really delete User “#{name}”?
SendMessage: Send message
SendMessageFail: Could not send message.
SendMessageSuccess subject@Text name@Text: Message “#{subject}” sent to “#{name}”.
Message: Message

NameField: Name
DescField: Description
HeadField: Header
FootField: Footer
LangField: Language
BodyField: Body
SubjectField: Subject

SubscriptionStatus: Status
ListActions: Actions
SubscriberActions: Actions
UserActions: Actions
SubscriberCount: Subscribers
SenderCount: Authors
Subscriptions: Subscriptions

Users: Users
EmailAddress: Email
Role: Role
UserRole: Role
ChangeUserRole: Change role
VerifiedStatus: Verification status
PromoteSubscriber: Promote to Author
DemoteSubscriber: Demote to Subscriber
ConfirmChangeRole name@Text oldRole@Text role@Text: Really change role of “#{name}” from “#{oldRole}” to “#{role}”?
ChangeRoleSuccess name@Text role@Text: Assigned role “#{role}” to “#{name}”.
ChangeRoleFail name@Text: Could not change role of “#{name}”.
ConfirmLogout: Really log out?

ActionSubscribe: subscribe
ActionUnsubscribe: unsubscribe
ActionSendMessage: send message
ActionEditList: edit list
ActionDeleteList: delete list
ActionDeleteUser: delete user

ChangeRoleButton: Change role
CancelButton: Cancel
ResetButton: Reset
SubmitButton: Submit
DeleteButton: Delete
LogoutButton: Logout
SendMessageButton: Send
NewListButton: Add
EditListButton: Update
UnsubscribeButton: Unsubscribe
AddEventButton: Add

UnsubscribeFail name@Text: Incorrect key, could not unsubscribe from list “#{name}”.
UnsubscribeSuccess name@Text: You have been unsubscribed from the list “#{name}”.
SubscribeSuccess name@Text: You have subscribed to the list “#{name}”.
Unsubscribe: Unsubscribe
UnsubscribeConfirm name@Text: Do you really want to unsubscribe from the list “#{name}”?

VerifyEmailSubject: minitrue: Verify your email address.
VerifyEmailBody key@Text url@Text: To verify our email address, visit #{url}.

LangEnglish: English
LangGerman: English

Events: Events
EventName: Name
EventLocation: Location
EventDate: Date
EventCategory: Category
EventTime: Time

CategoryName: Name
CategoryDescription: Description