Hello: Hello

List name@String: Mailing list “#{name}”
Lists: Mailing lists
AvailableLists: Available lists
NewList: New list
EditList: Edit list
EditListFail: Could not update list.
EditListSuccess name@String: List “#{name}” updated.
CreateListFail: Could not create list.
CreateListSuccess name@String: List “#{name}” created.
DeleteListFail: Could not delete list.
DeleteListSuccess name@String: List “#{name}” deleted.
DeleteListConfirm name@String: Really delete List “#{name}”?

NameField: Name
DescField: Description

CancelButton: Cancel
ResetButton: Reset
SubmitButton: Submit
DeleteButton: Delete