Hello: Hello
Login: Login
Logout: Logout
LoggedInAs name@Text: Logged in as “#{name}”
SetPassword: Change password
Register: Register

NavSubscriptions: List subscriptions
NavLists: Manage lists

RoleConsumer: User
RoleInnerCircle: Member of the Inner Circle™
RoleAdmin: Administrator

ListRoleNothing: not subscribed
ListRoleReceiver: Subscriber
ListRoleSender: Author

List name@Text: Mailing list “#{name}”
Lists: Mailing lists
AvailableLists: Available lists
NewList: New list
EditList: Edit list
EditListFail: Could not update list.
EditListSuccess name@Text: List “#{name}” updated.
CreateListFail: Could not create list.
CreateListSuccess name@Text: List “#{name}” created.
DeleteListFail: Could not delete list.
DeleteListSuccess name@Text: List “#{name}” deleted.
DeleteListConfirm name@Text: Really delete List “#{name}”?
SendMessage: Send message
SendMessageFail: Could not send message.
SendMessageSuccess subject@Text name@Text: Message “#{subject}” sent to “#{name}”.

NameField: Name
DescField: Description
BodyField: Body
SubjectField: Subject

SubscriptionStatus: Status
ListActions: Actions

ActionSubscribe: subscribe
ActionUnsubscribe: unsubscribe
ActionSendMessage: send message
ActionEditList: edit list

CancelButton: Cancel
ResetButton: Reset
SubmitButton: Submit
DeleteButton: Delete

VerifyEmailSubject: minitrue: Verify your email address.
VerifyEmailBody key@Text url@Text: URL: #{url}\nkey: #{key}