# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:PGUSER:minitrue"
  password: "_env:PGPASS:minitrue"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:minitrue"
  poolsize: "_env:PGPOOLSIZE:10"

copyright:        "<a href=\"https://github.com/mmarx/minitrue\">The Ministry of Truth</a>.<br> &copy; 2013, 2015 Maximilian Marx"
mailHost:         "_env:MAILHOST:localhost"
mailFromName:     "_env:MAILFROMNAME:The Ministry of Truth"
mailFromAddress:  "_env:MAILFROMADDRESS:minitrue@localhost"
mailListIdSuffix: "_env:MAILLISTIDSUFFIX:localhost"
